### ISSUE TITLE
I can't modify minqlbot.dll

### ISSUE THREAD

**Issue by Z3ROQL** [MinoMino/minqlbot#11]
If I try to modify a single character of the minqlbot.dll and then I try to inject it says "Failed to inject". I thought I hadn't some dependencies but everything was ok. How is it possible? And how can I modify the minqlbot.dll without breaking it?

**Comment by MinoMino** [comment]
I'm confused. What exactly are you trying to modify? minqlbot.dll is a compiled binary and isn't designed to be modified.

**Comment by Z3ROQL** [comment]
I just wanted to modify some colors. For example when you don't know how to use a command the bot shows you its usage in pink. I wanted to change it in blue, but when I did that the bot didn't work anymore.

**Comment by MinoMino** [comment]
That's hard-coded. You'd have to run the debug version so that it looks for plugin.py and minqlbot.py externally or compile a release build yourself. Perhaps there are applications out there that allow you to modify resources and have it correctly modify the PE headers and whatnot, but in any case, one of the other options is probably the way to go.
