### ISSUE TITLE
Failed to inject

### ISSUE THREAD

**Issue by BarelyMiSSeD** [MinoMino/minqlbot#2]
I am running Windows 7 Professional 64 bit. I installed the 32 bit versions of python and Visual C++ and I keep getting 'failed to inject' when I try to run Minjection.exe. I ran Dependency Walker and the only thing that shows as RED is the CPU (x64 in red) on the system dll files. This is a fresh installation of windows on a pc that I run Teamspeak and Murmur voice servers.

Any ideas what I need to do next? I would love to try out the server bot.

**Comment by jEKKThs** [comment]
Have you tried all six methods to inject? Give WInject a try.

2015-02-08 15:25 GMT+01:00 BarelyMiSSeD notifications@github.com:

**Comment by MinoMino** [comment]
Sounds like you're using the 64-bit version of Dependency Walker. It shouldn't be complaining about modules with different CPU types. Here's more or less how it should look like on the 32-bit version of it:

![](http://minomino.org/screenshots/2015-02-08_16-00-56.png)

**Comment by BarelyMiSSeD** [comment]
Thanks for the reply. I downloaded the 32-bit version of Dependency Walker and it now shows me that there is an error opening GPSVC.DLL even though the dll is in the system32 folder and loaded. That is the first thing listed in Dependency Walker and the only thing listed as an error.

How do I fix this? I thought myself pretty good with a computer, but apparently I still have a lot to learn.

**Comment by MinoMino** [comment]
Hmm. Not quite sure what's going on here. After googling GPSVC.DLL, it seems to work like IESHIMS.DLL in the sense that Dependency Walker will report it as missing, but in practice you can just ignore the error as it'll work anyway, so I don't think that's the issue here. I've also installed the bot without issues on a fresh W7 x64 install before too, so that shouldn't be the issue either.

The Boost DLL and the minhook DLL are both set to read-only and in the same folder as quakelive.exe, right? You could maybe try using Winject instead of my injector, but usually failing to inject is usually caused by DLLs not being found by quakelive.exe.

Frankly, I'm at a loss here. Perhaps you could post a screenshot of Dependency Walker so I could take a look at it just in case. The module list in the middle being the most important part, so expand it if you would. Full paths can be useful as well, which can be toggled with F9.

**Comment by BarelyMiSSeD** [comment]
You are a life saver Mino. I did have the 2 dll files in the quake live folder but somehow, while screwing wiht it, I lost the minhook.dll. I put that back in and it injected. THANK YOU!!!

Is there a way to set the bot to automatically give OPs to people when they join? I couldn't find that on the documentation page.

**Comment by MinoMino** [comment]
Good to hear you got it working.

By default, there's no function to do it automatically, but the bot is designed with the idea of allowing players to admin the server without having OP status. There are 5 permission levels. You can look at the [command list](http://minomino.org/quake/) (it's kinda outdated, but still) to give you a good idea of what commands are available at which level. To add players to the admin list, use !setperm <nickname> <permission_level>.

Example: !setperm mino 2

This would allow me to use a bunch of admin commands without having to have OP, allowing me to vote normally without having to pass or veto votes like you do when you have OP.
